### ISSUE TITLE
Update to React Native 0.52

### ISSUE THREAD

**Issue by geordidearns** [mjsolidarios/react-native-search-filter#10]
Hey!

Just creating this issue to update to react native 0.52 if you can, if if/when I find the time I will make a PR.

Thanks so much for creating this - super easy to get going and I'm now using it in my first React Native project :) so thanks for the hard work!

**Comment by mjsolidarios** [comment]
Thank you too @geordidearns! I'm currently busy with other projects but will surely include the update when I'm free.
