### ISSUE TITLE
error: bundling failed

### ISSUE THREAD

**Issue by uraniumreza** [mjsolidarios/react-native-search-filter#2]
error: bundling failed: "SyntaxError ... Unexpected token (188:28)"

`
if(this.state.contacts) const filteredContacts = this.state.contacts.filter(createFilter(this.state.searchString, KEYS_TO_FILTERS));
`

**Comment by mjsolidarios** [comment]
Hello @uraniumreza, can you give me the <b>steps</b> to trigger/reproduce the problem that are specific, and repeatable? What version of <b>react-native</b> are you using? Thanks!

**Comment by mjsolidarios** [comment]
Closing this issue now.
