### ISSUE TITLE
Indexes are getting changed after search

### ISSUE THREAD

**Issue by ghost** [mjsolidarios/react-native-search-filter#21]
Hi, I'm having text and checkbox in a view (Like checkbox in front of text).
After searching for a text, indexes are getting changed and because of this, not able to select checkbox at its original position. Please help !

**Comment by code4arpit** [comment]
Closing this issue as we can accomplish this using lodash api known as` _.findIndex`.

**Comment by Ovi** [comment]
@farrukhhashmi65 refer to [this link](https://lodash.com/docs/#findIndex) for documentation [lodash.com/docs/#findIndex](https://lodash.com/docs/#findIndex)
