### ISSUE TITLE
 Unable to use refs

### ISSUE THREAD

**Issue by shaktish** [mjsolidarios/react-native-search-filter#29]
Hi,

I'm unable to use ref for searchInput. I'm getting undefined. 

`ref={(ref) => { this.FirstInput = ref; }}

// when calling focus, I'm getting undefined
this.FirstInput.focus();
`

**Comment by mjsolidarios** [comment]
Hello @shaktish! Can you give more details so I can replicate the problem?

## Expected Behavior
## Actual Behavior
## Steps to Reproduce the Problem
  1.
  1.
  1.

**Comment by shaktish** [comment]
Hi MJ,

I resolved it by setting autoselect=true. 

The problem was after clicking select, keypad was not showing up so i needed to set auto-focus. 
So i tried using react refs. It didn't work, then i tried autoselect. It did the job

Thanks
