### ISSUE TITLE
Missing Peer Dependencies

### ISSUE THREAD

**Issue by hzburki** [mjsolidarios/react-native-search-filter#5]
On npm install ... I get the following warning ... 

`react-native-search-filter@0.1.2 requires a peer of react-native@0.41.2 but none is installed. You must install peer dependencies yourself.`

Using `"react": "16.0.0-alpha.12"` and `"react-native": "0.47.2"` ... 

This does not allow the app to boot ...

**Comment by mjsolidarios** [comment]
Sorry but I could not confirm this. I tested on a clean install using the following steps:

1. ```react-native init AwesomeProject --version 0.47.2```
1. ```yarn add react-native-search-filter```
1. ```react-native run-<android/ios>```

The app successfully runs even if you ignore the peer dependency warning.
![screenshot_2017-11-27-14-18-17](https://user-images.githubusercontent.com/7346165/33253377-10d22a12-d37e-11e7-987e-5d477edbaee9.png)

**Comment by hzburki** [comment]
Hello I ended up creating a custom filtering component. Thank you for your reply though. As no one else has this problem you can close this issue. I'll test again on my project when I get the time. If I have a problem I'll reopen the ticket with a detailed error log.

**Comment by mjsolidarios** [comment]
Thanks @hzburki and good luck!
